### ISSUE TITLE
Problem in kubectl outputs

### ISSUE THREAD

**Issue by smerschjohann** [benlau/ipylivebash#1]
HI,

first of all: thanks for this extesion, it helps a lot.

But there seems to be an issue if the output comes too fast or something. It might be the debouncing?
The output is only printed after I terminate the line or a new pod is created.

```bash
%%livebash
kubectl get pods -w
```

It works if I use the following code:

```python
import subprocess
import shlex
def run_command(command):
    process = subprocess.Popen(shlex.split(command), stdout=subprocess.PIPE)
    while True:
        output = process.stdout.readline()
        if output == '' and process.poll() is not None:
            break
        if output:
            print(output.strip().decode("utf-8") )
    rc = process.poll()
    return rc

run_command("kubectl get pods -w")
```

**Comment by benlau** [comment]
Hi @smerschjohann ,

Thank you for reporting the issue. The bug is indeed related to the debouncer. I have just modified the debouncer and run the script in a thread. The fix is available in the main branch.  I will test it for a few days. If no other problem is found, I will release a new version.

**Comment by smerschjohann** [comment]
@benlau Thank you, with the new version it works now :)
